server:
  port: 4040

spring:
  application:
    name: ToListmanagement

  datasource:
    url: jdbc:mysql://localhost:3306/managementTask?useSSL=false&serverTimezone=UTC
    username: root
    password: 192119

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  info:
    title: Api rest para gestão de tarefas
    version: 1.0
    description: Uma API de gestão de tarefas;

  swagger-ui:
    path: /docs
